apiVersion: v1
kind: Pod
metadata:
  name: init-container-demo
spec:
  containers:
  - name: main-application
    image: nginx
    
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
      
  initContainers:
  - name: my-pre-check-container
    image: busybox
   
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
      
    command: ["/bin/sh"]
    args: ["-c", "echo '<html><h1>Hello, This Webpage was created by Init Container</h1><html>' >> /work-dir/index.html"]
  
  volumes:
  - name: workdir
    emptyDir: {}

# kubectl apply -f 4.init-container.yml
# kubectl get pods
# kubectl get pods -o wide
# get the ip check via browser curl://contIP
# kubectl delete -f 4.init-container 