apiVersion: batch/v1
kind: Job
metadata:
  name: mypijob
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
#kubectl get all
#kubectl apply -f 8.0job.yml