apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
          #  imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure



# kubectl get all
# kubectl apply -f 8.2cronjob.yml
# kubectl get all
# kubectl get cronjob hello
# kubectl get jobs --watch
# kubectl get pods 
# kubectl logs <cronpodname>
# kubectl delete -f 8.cronjob.yml